apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "kube-review-prune.fullname" . }}
  labels:
    {{- include "kube-review-prune.labels" . | nindent 4 }}
spec:
  schedule: "@hourly"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "kube-review-prune.selectorLabels" . | nindent 12 }}
        spec:
          {{- if .Values.imagePullSecrets }}
          imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 16 }}
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
              command: ['{{ .Values.command }}']
              args:
                - '--ghToken={{ .Values.github.ghToken }}'
                - '--ghUserName={{ .Values.github.ghUserName }}'
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          restartPolicy: {{ .Values.restartPolicy | default "OnFailure" }}
          serviceAccountName: {{ include "kube-review-prune.serviceAccountName" . }}
