apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

secretGenerator:
- name: secret
  envs:
  - env.txt
  type: Opaque
  options:
    disableNameSuffixHash: true
  behavior: merge

patches:
  - path: deployment.yml
  - path: patches/deployment.patch.json
    target:
      kind: Deployment
      name: deployment